[package]
name = "wordlike-app"
version = "0.1.0"
edition = "2021"
build = "build.rs"  # This is the key addition to force the build script

[dependencies]
slint = { version = "1.7", features = ["std", "compat-1-2"] }

[build-dependencies]
slint-build = "1.7"